# SITE CONFIGURATION
title: Ivan Gufler
author: Ivan Gufler
description: > # Meta description of Homepage
  Ivan Gufler is a Ph.D. Candidate in Economics at Luiss Guido Carli. He received his master’s degree in 
  Economics and Finance (curriculum Quantitative Economics) from Ca’ Foscary University. He is currently a 
  visiting PhD student at the department of Finance of HEC Paris (until january 2024). He served as external 
  research collaborator at the Ca Foscari University of Venice within the project Incorporating environmental, 
  social and governance (ESG) criteria in credit analysis and ratings (EIBURS funding program). Previously he 
  worked as Research Assistant Intern at the Venice centre in Economic and Risk Analytics for public policies (VERA). 
  His research interests lie in the fields of Finance and Macrofinance.
#baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://igufler.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ivan Gufler
  links:
    - https://twitter.com/ivangufler
    - https://www.linkedin.com/in/ivan-gufler
    - https://github.com/igufler

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'CV', link: '/CV'}
  - {name: 'Research', link: '/research'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme

hero_img: posts/3.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

twitter_username: ivangufler # replace with your_twitter_username or comment to remove link from footer
github_username:  igufler # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
